"""Shared section definitions for HAEO element configuration."""

# ruff: noqa: I001

from .common import (
    CONF_CONNECTION,
    CommonConfig,
    CommonData,
    ConnectedCommonConfig,
    ConnectedCommonData,
    SECTION_COMMON,
    build_common_fields,
    common_section,
)
from .curtailment import (
    CurtailmentConfig,
    CurtailmentData,
    SECTION_CURTAILMENT,
    build_curtailment_fields,
    curtailment_section,
)
from .efficiency import (
    EfficiencyConfig,
    EfficiencyData,
    SECTION_EFFICIENCY,
    build_efficiency_fields,
    efficiency_section,
)
from .forecast import (
    CONF_FORECAST,
    ForecastConfig,
    ForecastData,
    SECTION_FORECAST,
    build_forecast_fields,
    forecast_section,
)
from .limits import LimitsConfig, LimitsData, SECTION_LIMITS, build_limits_fields, limits_section
from .partitioning import (
    PartitioningConfig,
    PartitioningData,
    SECTION_PARTITIONING,
    build_partitioning_fields,
    partitioning_section,
)
from .power_limits import (
    CONF_MAX_POWER_SOURCE_TARGET,
    CONF_MAX_POWER_TARGET_SOURCE,
    PowerLimitsConfig,
    PowerLimitsData,
    PowerLimitsPairConfig,
    PowerLimitsPairData,
    SECTION_POWER_LIMITS,
    build_power_limits_fields,
    power_limits_section,
)
from .pricing import (
    CONF_PRICE_SOURCE_TARGET,
    CONF_PRICE_TARGET_SOURCE,
    PricingConfig,
    PricingData,
    PricingPairConfig,
    PricingPairData,
    SECTION_PRICING,
    build_pricing_fields,
    pricing_section,
)
from .role import RoleConfig, RoleData, SECTION_ROLE, build_role_fields, role_section
from .storage import (
    CONF_CAPACITY,
    CONF_INITIAL_CHARGE,
    CONF_INITIAL_CHARGE_PERCENTAGE,
    SECTION_STORAGE,
    StorageChargeConfig,
    StorageChargeData,
    StorageConfig,
    StorageData,
    StorageSocConfig,
    StorageSocData,
    build_storage_fields,
    storage_section,
)

__all__ = [
    "CONF_CAPACITY",
    "CONF_CONNECTION",
    "CONF_FORECAST",
    "CONF_INITIAL_CHARGE",
    "CONF_INITIAL_CHARGE_PERCENTAGE",
    "CONF_MAX_POWER_SOURCE_TARGET",
    "CONF_MAX_POWER_TARGET_SOURCE",
    "CONF_PRICE_SOURCE_TARGET",
    "CONF_PRICE_TARGET_SOURCE",
    "SECTION_COMMON",
    "SECTION_CURTAILMENT",
    "SECTION_EFFICIENCY",
    "SECTION_FORECAST",
    "SECTION_LIMITS",
    "SECTION_PARTITIONING",
    "SECTION_POWER_LIMITS",
    "SECTION_PRICING",
    "SECTION_ROLE",
    "SECTION_STORAGE",
    "CommonConfig",
    "CommonData",
    "ConnectedCommonConfig",
    "ConnectedCommonData",
    "CurtailmentConfig",
    "CurtailmentData",
    "EfficiencyConfig",
    "EfficiencyData",
    "ForecastConfig",
    "ForecastData",
    "LimitsConfig",
    "LimitsData",
    "PartitioningConfig",
    "PartitioningData",
    "PowerLimitsConfig",
    "PowerLimitsData",
    "PowerLimitsPairConfig",
    "PowerLimitsPairData",
    "PricingConfig",
    "PricingData",
    "PricingPairConfig",
    "PricingPairData",
    "RoleConfig",
    "RoleData",
    "StorageChargeConfig",
    "StorageChargeData",
    "StorageConfig",
    "StorageData",
    "StorageSocConfig",
    "StorageSocData",
    "build_common_fields",
    "build_curtailment_fields",
    "build_efficiency_fields",
    "build_forecast_fields",
    "build_limits_fields",
    "build_partitioning_fields",
    "build_power_limits_fields",
    "build_pricing_fields",
    "build_role_fields",
    "build_storage_fields",
    "common_section",
    "curtailment_section",
    "efficiency_section",
    "forecast_section",
    "limits_section",
    "partitioning_section",
    "power_limits_section",
    "pricing_section",
    "role_section",
    "storage_section",
]
